// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG4YHqU-imqj_KpD_Bw6vQQYwxskoBb6I',
    appId: '1:405742262356:web:aa95d456123a428f8735c1',
    messagingSenderId: '405742262356',
    projectId: 'fruiteshop-61e48',
    authDomain: 'fruiteshop-61e48.firebaseapp.com',
    storageBucket: 'fruiteshop-61e48.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpolh_TF4MwpSDNp7HsJ6j6_JODUhyFt0',
    appId: '1:405742262356:android:52a2005b5cee0f318735c1',
    messagingSenderId: '405742262356',
    projectId: 'fruiteshop-61e48',
    storageBucket: 'fruiteshop-61e48.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX-G9fYZ1B6doQDriuyu0qLKoa-DerwRE',
    appId: '1:405742262356:ios:e98a5e171b1d099d8735c1',
    messagingSenderId: '405742262356',
    projectId: 'fruiteshop-61e48',
    storageBucket: 'fruiteshop-61e48.appspot.com',
    iosBundleId: 'com.example.fruitApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX-G9fYZ1B6doQDriuyu0qLKoa-DerwRE',
    appId: '1:405742262356:ios:e98a5e171b1d099d8735c1',
    messagingSenderId: '405742262356',
    projectId: 'fruiteshop-61e48',
    storageBucket: 'fruiteshop-61e48.appspot.com',
    iosBundleId: 'com.example.fruitApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBG4YHqU-imqj_KpD_Bw6vQQYwxskoBb6I',
    appId: '1:405742262356:web:c2a24706736d94d98735c1',
    messagingSenderId: '405742262356',
    projectId: 'fruiteshop-61e48',
    authDomain: 'fruiteshop-61e48.firebaseapp.com',
    storageBucket: 'fruiteshop-61e48.appspot.com',
  );
}
